import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,CalendarDays,Check,ChevronLeft,ChevronRight,Copy,MapPin,MessageCircle,Sparkles,Star}from'lucide-react';
import'./styles.css';

type Item={name:string;description:string;image:string};
const services:Item[]=[
{name:'Manicure',description:'Detailed care, shaping and flawless polish.',image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=85'},
{name:'Pedicure',description:'A restorative finish for beautiful, polished toes.',image:'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=85'},
{name:'Acrylic',description:'Sculpted extensions tailored to your desired look.',image:'https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=900&q=85'},
{name:'Gel',description:'A glossy, durable finish with rich lasting colour.',image:'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=900&q=85'},
{name:'Press-ons',description:'Custom reusable sets designed just for you.',image:'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=900&q=85'},
{name:'Removal',description:'Gentle professional removal that protects your nails.',image:'https://images.unsplash.com/photo-1619451334792-150fd785ee74?auto=format&fit=crop&w=900&q=85'},
{name:'Refill',description:'Refresh your existing set and restore its finish.',image:'https://images.unsplash.com/photo-1612887390768-f29b5c7f5c26?auto=format&fit=crop&w=900&q=85'},
{name:'Nail art',description:'Personalised details, accents and statement designs.',image:'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=900&q=85'}
];
const shapes=['Square','Almond','Oval','Coffin','Stiletto','Round'];
const lengths=['Short','Medium','Long','Extra-long'];
const looks:Item[]=[
{name:'French',description:'Clean and timeless',image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=85'},
{name:'Chrome',description:'Mirror-like shine',image:'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=900&q=85'},
{name:'Cat-eye',description:'Magnetic dimension',image:'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=900&q=85'},
{name:'Ombre',description:'Soft colour blend',image:'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=900&q=85'},
{name:'Glitter',description:'Light-catching sparkle',image:'https://images.unsplash.com/photo-1612887390768-f29b5c7f5c26?auto=format&fit=crop&w=900&q=85'},
{name:'Freestyle',description:'Artist-led creation',image:'https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=900&q=85'}
];
const colours=['#efe0d5','#f2a2ba','#c92971','#8b2551','#5a1f3a','#171217','#8056a8','#f5c451'];
const stepNames=['Service','Shape','Length','Design','Date','Details'];

function App(){
const[step,setStep]=useState(0),[service,setService]=useState('Gel'),[shape,setShape]=useState('Almond'),[length,setLength]=useState('Medium'),[style,setStyle]=useState('Cat-eye'),[colour,setColour]=useState('#8b2551'),[customColour,setCustomColour]=useState(''),[date,setDate]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[notes,setNotes]=useState(''),[copied,setCopied]=useState(false);
const chosenService=services.find(x=>x.name===service)!;
const summary=useMemo(()=>`Hello Joy AD! I would like to request a nail appointment with DE_JOY ARTISTRY.\n\nName: ${name||'Not provided'}\nPhone: ${phone||'Not provided'}\nPreferred date: ${date||'Not selected'}\nService: ${service}\nShape: ${shape}\nLength: ${length}\nDesign: ${style}\nPreferred colour: ${customColour||colour}\nNotes: ${notes||'None'}\n\nPlease let me know your availability and final price.`,[name,phone,date,service,shape,length,style,colour,customColour,notes]);
const copy=async()=>{await navigator.clipboard.writeText(summary);setCopied(true);setTimeout(()=>setCopied(false),2200)};
const next=()=>setStep(s=>Math.min(5,s+1));const back=()=>setStep(s=>Math.max(0,s-1));
return <div className="site"><Nav/><main>
<section className="hero" id="home"><div className="hero-noise"/><div className="hero-copy"><div className="kicker"><Sparkles size={14}/> BESPOKE NAIL ARTISTRY · ABUJA</div><h1>Your nails.<br/><em>Your statement.</em></h1><p>Thoughtfully designed sets, made to express you. Choose your service and dream look, then complete the details with Joy on WhatsApp.</p><div className="hero-actions"><a className="button dark" href="#booking">Build your set <ArrowRight/></a><a className="text-link" href="#inspiration">Explore designs <ChevronRight/></a></div><div className="hero-trust"><span><Star fill="currentColor"/> Personalised service</span><span><MapPin/> Abuja, Nigeria</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=1300&q=90" alt="Luxury nail art by DE_JOY ARTISTRY"/><div className="glass-card"><span>THE DE_JOY EXPERIENCE</span><strong>Every set is custom.</strong><small>No fixed price · Confirmed personally</small></div><div className="roundel">BOOK · CREATE · SHINE ·</div></div></section>
<section className="marquee"><div>MANICURE <i/> PEDICURE <i/> ACRYLIC <i/> GEL <i/> PRESS-ONS <i/> NAIL ART <i/></div></section>
<section className="services section" id="services"><Header eyebrow="SERVICES" title="Your vision, expertly finished." body="From subtle everyday polish to bold sculpted art, select the starting point for a set made entirely around you."/><div className="service-grid">{services.map((x,i)=><button key={x.name} onClick={()=>{setService(x.name);setStep(1);document.querySelector('#booking')?.scrollIntoView({behavior:'smooth'})}} className={service===x.name?'active':''}><div className="service-image"><img src={x.image} alt={x.name}/><span>0{i+1}</span></div><div><h3>{x.name}</h3><p>{x.description}</p><span className="discover">Select service <ArrowRight/></span></div></button>)}</div></section>
<section className="editorial" id="inspiration"><div className="editorial-copy"><div className="kicker light">FIND YOUR SIGNATURE</div><h2>Art at<br/>your fingertips.</h2><p>Bring your inspiration or let Joy create freely. Each detail is discussed before your appointment is confirmed.</p><a href="#booking" className="button light-button">Choose your look <ArrowRight/></a></div><div className="editorial-gallery">{looks.slice(0,3).map((x,i)=><figure className={`shot shot-${i+1}`} key={x.name}><img src={x.image} alt={`${x.name} nail inspiration`}/><figcaption>{x.name}</figcaption></figure>)}</div></section>
<section className="booking section" id="booking"><Header eyebrow="YOUR APPOINTMENT" title="Build your perfect set." body="Six simple steps. Your choices become a ready-to-send enquiry for Joy to review and price personally." centered/><div className="booking-shell"><div className="progress-wrap"><div className="progress-top"><span>Step {step+1} of 6</span><b>{stepNames[step]}</b></div><div className="progress"><i style={{width:`${((step+1)/6)*100}%`}}/></div><div className="steps">{stepNames.map((x,i)=><button key={x} className={i===step?'current':i<step?'complete':''} onClick={()=>setStep(i)}><span>{i<step?<Check/>:i+1}</span>{x}</button>)}</div></div><div className="builder"><div className="stage"><StepContent step={step} service={service} setService={setService} shape={shape} setShape={setShape} length={length} setLength={setLength} style={style} setStyle={setStyle} colour={colour} setColour={setColour} customColour={customColour} setCustomColour={setCustomColour} date={date} setDate={setDate} name={name} setName={setName} phone={phone} setPhone={setPhone} notes={notes} setNotes={setNotes}/><div className="stage-nav">{step>0?<button className="button ghost" onClick={back}><ChevronLeft/> Back</button>:<span/>}{step<5?<button className="button dark" onClick={next}>Continue <ChevronRight/></button>:<button className="button whatsapp" onClick={copy}><MessageCircle/>{copied?'Request copied':'Copy for WhatsApp'}</button>}</div></div><aside><div className="summary-image"><img src={chosenService.image} alt="Your chosen service"/><span>YOUR SELECTION</span></div><h3>{service} appointment</h3><dl><div><dt>Shape</dt><dd>{shape}</dd></div><div><dt>Length</dt><dd>{length}</dd></div><div><dt>Design</dt><dd>{style}</dd></div><div><dt>Date</dt><dd>{date||'Choose a date'}</dd></div></dl><p><Sparkles/> Final price is discussed with Joy after reviewing your choices.</p></aside></div></div></section>
<section className="final-cta"><span className="kicker light">DE_JOY ARTISTRY</span><h2>Ready to make<br/>your nails shine?</h2><a className="button light-button" href="#booking">Start your booking <ArrowRight/></a></section>
</main><Footer/></div>}

function StepContent(p:any){if(p.step===0)return <Panel title="What can we do for you?" hint="Select one primary service. You can mention extras in your notes."><div className="select-cards service-select">{services.map(x=><button className={p.service===x.name?'selected':''} onClick={()=>p.setService(x.name)} key={x.name}><img src={x.image} alt=""/><div><b>{x.name}</b><small>{x.description}</small></div>{p.service===x.name&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===1)return <Panel title="Choose your shape" hint="Not certain? Pick the closest option and Joy can advise you."><div className="shape-grid">{shapes.map((x,i)=><button className={p.shape===x?'selected':''} onClick={()=>p.setShape(x)} key={x}><span className={`nail nail-${i}`}/><b>{x}</b>{p.shape===x&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===2)return <Panel title="How long should we go?" hint="Your final length can be adjusted during consultation."><div className="length-grid">{lengths.map((x,i)=><button className={p.length===x?'selected':''} onClick={()=>p.setLength(x)} key={x}><span style={{height:42+i*20}}/><b>{x}</b><small>{['Natural and practical','A balanced everyday look','Extra room for expression','Maximum drama and detail'][i]}</small>{p.length===x&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===3)return <Panel title="Find your finish" hint="Choose a direction, then add any specific details below."><div className="look-grid">{looks.map(x=><button className={p.style===x.name?'selected':''} onClick={()=>p.setStyle(x.name)} key={x.name}><img src={x.image} alt=""/><span><b>{x.name}</b><small>{x.description}</small></span>{p.style===x.name&&<i><Check/></i>}</button>)}</div><label className="field"><span>Colour direction</span><div className="swatches">{colours.map(x=><button type="button" aria-label={`Select ${x}`} className={p.colour===x?'chosen':''} style={{background:x}} onClick={()=>{p.setColour(x);p.setCustomColour('')}} key={x}/>}</div><input value={p.customColour} onChange={(e:any)=>p.setCustomColour(e.target.value)} placeholder="Or describe a colour, e.g. milky pink"/></label></Panel>;
if(p.step===4)return <Panel title="When would you prefer?" hint="This is a request only. Joy will confirm availability with you."><div className="date-card"><CalendarDays/><div><span>Preferred appointment date</span><input type="date" min={new Date().toISOString().slice(0,10)} value={p.date} onChange={(e:any)=>p.setDate(e.target.value)}/></div></div><div className="notice"><Sparkles/><p><b>Appointments are personally confirmed.</b><br/>Your chosen date is not reserved until Joy responds on WhatsApp.</p></div></Panel>;
return <Panel title="Tell us about you" hint="These details will be included in your WhatsApp booking request."><div className="form-grid"><label className="field"><span>Your name *</span><input value={p.name} onChange={(e:any)=>p.setName(e.target.value)} placeholder="Full name"/></label><label className="field"><span>WhatsApp number</span><input value={p.phone} onChange={(e:any)=>p.setPhone(e.target.value)} placeholder="e.g. +234..."/></label><label className="field full"><span>Notes or inspiration</span><textarea value={p.notes} onChange={(e:any)=>p.setNotes(e.target.value)} placeholder="Tell Joy about colours, art details, occasion, or anything else..."/></label></div><div className="notice"><MessageCircle/><p><b>Your request is ready.</b><br/>Copy it below, then paste it into your chat with Joy AD to discuss availability and price.</p></div></Panel>}
function Panel({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <div className="panel"><div className="panel-head"><h3>{title}</h3><p>{hint}</p></div>{children}</div>}
function Header({eyebrow,title,body,centered=false}:{eyebrow:string;title:string;body:string;centered?:boolean}){return <header className={`section-head ${centered?'centered':''}`}><span className="kicker">{eyebrow}</span><h2>{title}</h2><p>{body}</p></header>}
function Nav(){return <nav><a className="logo" href="#home">DE_<strong>JOY</strong><small>ARTISTRY</small></a><div className="nav-links"><a href="#services">Services</a><a href="#inspiration">Inspiration</a><a href="#booking">Book</a></div><a className="nav-cta" href="#booking">Book appointment <ArrowRight/></a></nav>}
function Footer(){return <footer><a className="logo" href="#home">DE_<strong>JOY</strong><small>ARTISTRY</small></a><p>Bespoke nail artistry in Abuja, Nigeria.<br/>Appointments by personal confirmation.</p><div><a href="#services">Services</a><a href="#inspiration">Inspiration</a><a href="#booking">Book appointment</a></div><small>© 2026 DE_JOY ARTISTRY · Final prices depend on the selected service and design.</small></footer>}
createRoot(document.getElementById('root')!).render(<App/>);
