import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,CalendarDays,Check,ChevronLeft,ChevronRight,Menu,MessageCircle,Sparkles,X}from'lucide-react';
import'./styles.css';

type Choice={name:string;description:string;image:string};
const refillImage='https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1200&q=90';
const services:Choice[]=[
{name:'Manicure',description:'Nail care, shaping and polish',image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=82'},
{name:'Pedicure',description:'Restorative care for polished toes',image:'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=82'},
{name:'Acrylic',description:'Custom sculpted extensions',image:'https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=900&q=82'},
{name:'Gel',description:'Glossy and long-lasting colour',image:'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=900&q=82'},
{name:'Press-ons',description:'Reusable sets made for you',image:'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=900&q=82'},
{name:'Removal',description:'Gentle professional removal',image:'https://images.unsplash.com/photo-1619451334792-150fd785ee74?auto=format&fit=crop&w=900&q=82'},
{name:'Refill',description:'A fresh fill and flawless finish',image:refillImage},
{name:'Nail art',description:'Bespoke art and details',image:'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=900&q=82'}
];
const designs:Choice[]=[
{name:'French',description:'Timeless',image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=82'},
{name:'Chrome',description:'Reflective',image:'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=800&q=82'},
{name:'Cat-eye',description:'Dimensional',image:'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=82'},
{name:'Ombre',description:'Soft blend',image:'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=800&q=82'},
{name:'Glitter',description:'Sparkle',image:'https://images.unsplash.com/photo-1612887390768-f29b5c7f5c26?auto=format&fit=crop&w=800&q=82'},
{name:'Freestyle',description:'Artist-led',image:'https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=800&q=82'}
];
const shapes=['Square','Almond','Oval','Coffin','Stiletto','Round'];
const lengths=['Short','Medium','Long','Extra-long'];
const steps=['Service','Shape','Length','Design','Date','Details'];
const swatches=['Nude','Pink','Red','Burgundy','Black','Purple','Blue','Gold'];
const swatchHex=['#e9d3c3','#efa0bc','#bf234b','#75233e','#171417','#765197','#4b688e','#d1aa4f'];

function App(){
const[menu,setMenu]=useState(false),[step,setStep]=useState(0),[service,setService]=useState('Gel'),[shape,setShape]=useState('Almond'),[length,setLength]=useState('Medium'),[design,setDesign]=useState('Cat-eye'),[colour,setColour]=useState('Burgundy'),[customColour,setCustomColour]=useState(''),[date,setDate]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[notes,setNotes]=useState(''),[copied,setCopied]=useState(false);
const selected=services.find(item=>item.name===service)!;
const summary=useMemo(()=>`Hello Joy AD! I would like to request an appointment with DE_JOY ARTISTRY.\n\nName: ${name||'Not provided'}\nPhone: ${phone||'Not provided'}\nPreferred date: ${date||'Not selected'}\nService: ${service}\nShape: ${shape}\nLength: ${length}\nDesign: ${design}\nColour: ${customColour||colour}\nNotes: ${notes||'None'}\n\nPlease confirm availability and the final price.`,[name,phone,date,service,shape,length,design,colour,customColour,notes]);
const copy=async()=>{await navigator.clipboard.writeText(summary);setCopied(true);window.setTimeout(()=>setCopied(false),2200)};
const selectService=(value:string,jump=false)=>{setService(value);if(jump){setStep(1);document.querySelector('#booking')?.scrollIntoView({behavior:'smooth'})}};
return <div className="app"><Header open={menu} setOpen={setMenu}/><main>
<section className="hero" id="home"><div className="hero-content"><div className="eyebrow"><span/> BESPOKE NAIL ARTISTRY · ABUJA</div><h1>Your nails.<br/><em>Your statement.</em></h1><p>Thoughtfully designed sets, made to express you. Choose your service and dream look, then complete the details with Joy on WhatsApp.</p><div className="hero-actions"><a className="btn btn-primary" href="#booking">Build your set <ArrowRight/></a><a className="link" href="#work">Explore designs <span aria-hidden="true">&gt;</span></a></div></div><div className="hero-media"><img src="https://images.unsplash.com/photo-1604902396830-aca29e19b067?auto=format&fit=crop&w=1500&q=88" alt="Professional manicure"/><div className="hero-card"><small>NOW BOOKING</small><b>Appointments in Abuja</b><span>Choose a preferred date</span></div></div></section>
<section className="intro section"><div><span className="section-label">THE STUDIO</span><h2>Nails that feel<br/>like <em>you.</em></h2></div><div><p>From clean, minimal finishes to detailed statement sets, DE_JOY ARTISTRY brings thoughtful technique and a personal approach to every appointment.</p><a className="link dark-link" href="#services">Explore services <ArrowRight/></a></div></section>
<section className="services section" id="services"><SectionTitle index="01" label="SERVICES" title="Choose your starting point" text="Select a service to begin. Your exact design and final price are confirmed personally with Joy."/><div className="service-list">{services.map((item,index)=><button className={service===item.name?'active':''} onClick={()=>selectService(item.name,true)} key={item.name}><span className="service-number">{String(index+1).padStart(2,'0')}</span><img src={item.image} alt={`${item.name} service`} onError={(event)=>{event.currentTarget.src=refillImage}}/><span className="service-copy"><b>{item.name}</b><small>{item.description}</small></span><ArrowRight/></button>)}</div></section>
<section className="work section" id="work"><SectionTitle index="02" label="SELECTED WORK" title="Find your direction" text="Choose a look as your starting point. Bring your own reference or leave the creative direction to Joy."/><div className="work-grid">{designs.slice(0,4).map((item,index)=><figure className={`work-${index+1}`} key={item.name}><img src={item.image} alt={`${item.name} nail design`}/><figcaption><b>{item.name}</b><span>{item.description}</span></figcaption></figure>)}</div></section>
<section className="booking-section section" id="booking"><SectionTitle index="03" label="BOOKING ENQUIRY" title="Build your appointment" text="Make your selections in six quick steps. Nothing is reserved until Joy confirms your date and price on WhatsApp."/><div className="booking-app"><div className="app-header"><div><span>YOUR BOOKING</span><b>Step {step+1} of {steps.length}</b></div><div className="meter"><i style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div className="desktop-steps">{steps.map((item,index)=><button onClick={()=>setStep(index)} className={index===step?'current':index<step?'done':''} key={item}><span>{index<step?<Check/>:index+1}</span>{item}</button>)}</div></div><div className="app-body"><section className="app-stage"><BookingStep step={step} service={service} setService={setService} shape={shape} setShape={setShape} length={length} setLength={setLength} design={design} setDesign={setDesign} colour={colour} setColour={setColour} customColour={customColour} setCustomColour={setCustomColour} date={date} setDate={setDate} name={name} setName={setName} phone={phone} setPhone={setPhone} notes={notes} setNotes={setNotes}/><div className="app-actions">{step>0?<button className="btn btn-secondary" onClick={()=>setStep(step-1)}><ChevronLeft/> Back</button>:<span/>}{step<5?<button className="btn btn-primary continue-button" onClick={()=>setStep(step+1)}>Continue <ChevronRight/></button>:<button className="btn btn-whatsapp" onClick={copy}><MessageCircle/>{copied?'Copied':'Copy for WhatsApp'}</button>}</div></section><aside><span className="summary-label">YOUR SELECTION</span><img src={selected.image} alt="Selected nail service" onError={(event)=>{event.currentTarget.src=refillImage}}/><h3>{service}</h3><dl><div><dt>Shape</dt><dd>{shape}</dd></div><div><dt>Length</dt><dd>{length}</dd></div><div><dt>Design</dt><dd>{design}</dd></div><div><dt>Colour</dt><dd>{customColour||colour}</dd></div><div><dt>Preferred date</dt><dd>{date||'Not selected'}</dd></div></dl><p><Sparkles/> Final price is provided after Joy reviews your selections.</p></aside></div></div></section>
<section className="closing"><span>DE_JOY ARTISTRY · ABUJA</span><h2>Your next set<br/>starts here.</h2><a className="btn btn-light" href="#booking">Book an appointment <ArrowRight/></a></section>
</main><Footer/></div>}

function Header({open,setOpen}:{open:boolean;setOpen:(value:boolean)=>void}){const close=()=>setOpen(false);return <><header className="header"><a className="logo" href="#home" onClick={close}><b>DE_JOY</b><span>ARTISTRY</span></a><nav><a href="#services">Services</a><a href="#work">Inspiration</a><a href="#services">Store</a><a href="#booking">Booking</a></nav><a className="header-cta" href="#booking">Book now <ArrowRight/></a><button className="menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header><div className={`mobile-menu ${open?'open':''}`}><div className="mobile-links"><a href="#home" onClick={close}><span>01</span>Home</a><a href="#services" onClick={close}><span>02</span>Services</a><a href="#work" onClick={close}><span>03</span>Inspiration</a><a href="#services" onClick={close}><span>04</span>Store</a><a href="#booking" onClick={close}><span>05</span>Booking</a></div><div className="mobile-menu-foot"><p>DE_JOY ARTISTRY</p><span>Abuja, Nigeria</span></div></div></>}
function SectionTitle({index,label,title,text}:{index:string;label:string;title:string;text:string}){return <header className="section-title"><div><span className="section-index">{index}</span><span className="section-label">{label}</span></div><h2>{title}</h2><p>{text}</p></header>}
function BookingStep(p:any){if(p.step===0)return <Panel title="Select a service" text="What would you like to book?"><div className="option-grid service-options">{services.map(item=><button className={p.service===item.name?'selected':''} onClick={()=>p.setService(item.name)} key={item.name}><img src={item.image} alt={`${item.name} service`} onError={(event)=>{event.currentTarget.src=refillImage}}/><span><b>{item.name}</b><small>{item.description}</small></span>{p.service===item.name&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===1)return <Panel title="Choose a shape" text="Select the closest shape to your preferred look."><div className="shape-options">{shapes.map((item,index)=><button className={p.shape===item?'selected':''} onClick={()=>p.setShape(item)} key={item}><span className={`nail-shape shape-${index}`}/><b>{item}</b>{p.shape===item&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===2)return <Panel title="Choose a length" text="You can adjust the exact length during consultation."><div className="length-options">{lengths.map((item,index)=><button className={p.length===item?'selected':''} onClick={()=>p.setLength(item)} key={item}><span style={{height:38+index*18}}/><b>{item}</b><small>{['Easy everyday wear','Balanced and versatile','More room for art','Maximum impact'][index]}</small>{p.length===item&&<i><Check/></i>}</button>)}</div></Panel>;
if(p.step===3)return <Panel title="Choose your design" text="Pick a direction, colour and add more detail later."><div className="design-options">{designs.map(item=><button className={p.design===item.name?'selected':''} onClick={()=>p.setDesign(item.name)} key={item.name}><img src={item.image} alt=""/><span><b>{item.name}</b><small>{item.description}</small></span>{p.design===item.name&&<i><Check/></i>}</button>)}</div><div className="colour-field"><label>Colour direction</label><div>{swatches.map((item,index)=><button className={p.colour===item?'selected':''} onClick={()=>{p.setColour(item);p.setCustomColour('')}} aria-label={item} style={{background:swatchHex[index]}} key={item}/>)}</div><input value={p.customColour} onChange={(e:any)=>p.setCustomColour(e.target.value)} placeholder="Or describe your preferred colour"/></div></Panel>;
if(p.step===4)return <Panel title="Choose a preferred date" text="Your date is a request until Joy confirms availability."><label className="date-input"><CalendarDays/><span><small>PREFERRED DATE</small><input type="date" min={new Date().toISOString().slice(0,10)} value={p.date} onChange={(e:any)=>p.setDate(e.target.value)}/></span></label><div className="info-box"><Sparkles/><p><b>Personal confirmation</b><span>Joy will review the date and confirm availability with you on WhatsApp.</span></p></div></Panel>;
return <Panel title="Your details" text="Add the contact information for your booking request."><div className="details-grid"><label><span>Full name *</span><input value={p.name} onChange={(e:any)=>p.setName(e.target.value)} placeholder="Your full name"/></label><label><span>WhatsApp number</span><input value={p.phone} onChange={(e:any)=>p.setPhone(e.target.value)} placeholder="+234..."/></label><label className="wide"><span>Notes or inspiration</span><textarea value={p.notes} onChange={(e:any)=>p.setNotes(e.target.value)} placeholder="Describe your colour, details, occasion or inspiration..."/></label></div><div className="info-box"><MessageCircle/><p><b>Ready to send</b><span>Copy your request and paste it into the WhatsApp chat with Joy AD.</span></p></div></Panel>}
function Panel({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div className="panel"><header><h3>{title}</h3><p>{text}</p></header>{children}</div>}
function Footer(){return <footer><div><a className="logo" href="#home"><b>DE_JOY</b><span>ARTISTRY</span></a><p>Bespoke nail artistry in Abuja, Nigeria.</p></div><nav><a href="#services">Services</a><a href="#work">Inspiration</a><a href="#services">Store</a><a href="#booking">Booking</a></nav><small>© 2026 DE_JOY ARTISTRY</small></footer>}
createRoot(document.getElementById('root')!).render(<App/>);
